### PR TITLE
New implementation

### PR DESCRIPTION
**Pull request by vitorsilvalima**
Hi Matheus,

We have implemented a new version of the library that meets some of the features of the Global Identity API. We now have a library that has both authorization and management capabilities.

Below are the methods we've implemented:
```js
import GlobalIdentity from 'node-global-identity';

const gim = new GlobalIdentity({
  applicationKey: 'YOUR-APPLICATION-KEY',
  apiKey: 'YOUR-API-KEY',
  baseURL: 'GLOBAL-IDENTITY-URL',
});

## Authorization 

```ts
* gim.Authorization.authenticateUser( email: string, password:string) : Promise
* gim.Authorization.validateToken (token: string): Promise
* gim.Authorization.renewToken (oldToken: string): Promise
* gim.Authorization.isUserInRoles (userKey:string, roles: [string]): Promise
* gim.Authorization.recoverPassword (email:string): Promise
```

## Management

```ts
* gim.Management.addUser (email: string, fullName: string, comment?:string): Promise
* gim.Management.deleteUser (email: string)
* gim.Management.getUserRoles (email: string): Promise
* gim.Management.associateRolesToUser (email: string, roles: string[]): Promise
* gim.Management.dissociateUserFromRole (email: string, roleName: string): Promise

We have to change the old public interface of the library in order to have both Authorization and
 Management. However, we changed the version of the library in order to not break clients which are using the old version of the library.

Can you please have a look at what we have done

### CODE REVIEW

**Comment by mguilarducci** [comment]
Should we reconfigure our CI service?

**Comment by vitorsilvalima** [comment]
@mguilarducci  I have already updated our travis.yaml file. However, we still need to setup the correct environment variables on travis. 

ps: I just added the correct env variables and now the tests would pass.

**Comment by vitorsilvalima** [comment]
@MarcoWorms I totally agree. I will try to fix that before merging this PR. It was my fault cause I did not really understand our git style guide.

**Comment by mguilarducci** [comment]
> Did the last configuration also build and send a new version to npm?
Yes! The lib was deployed when a tag was applied to some commit.
We used encrypt data to store the apikey into the travis file. I don't know if this key is correct yet...

**Comment by vitorsilvalima** [comment]
I have encrypted  the environment variables however, as stated by the travis documentations:
"Before adding sensitive data such as API credentials to your .travis.yml you need to encrypt it. Encrypted variables are not available to untrusted builds such as pull requests coming from another repository."
So that is the reason for why some of the tests are failing

**Pull request merged**
